
### Get all the movies:
GET http://localhost:3000/api/movies  

### Get movie by ID:
GET http://localhost:3000/api/movies/6330cd44-c757-11ee-82e3-7e8b40a06003

### Get movie by genre:
GET http://localhost:3000/api/movies?genre=DRAMA

### Create a movie with POST:
POST http://localhost:3000/api/movies
Content-Type: application/json

{
  "title": "test",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ],
  "rate": 5.0
}

### Create a bad request with POST:
POST http://localhost:3000/api/movies
Content-Type: application/json

{
  "sql": "SELECT * FROM users",
  "title": "The Godfather"
 
}

### Update part of a movie:
PATCH http://localhost:3000/api/movies/4f7bce96-c835-11ee-a3ce-2a1d1101d31e
Content-Type: application/json

{
  "year": 1975,
  "genre": [
    "Sci-Fi",
    "Adventure"
  ]
}

### Delete a movie:
DELETE http://localhost:3000/api/movies/4f7bce96-c835-11ee-a3ce-2a1d1101d31e